PATH_CPP = .\Cpp_files
PATH_HEADER = .\Headers\
HEADERS_NAME = GraphDump.h Differentiator.h DiffProgramm.h ReadParcer.h Simplifier.h LexicalAnalysis.h
HEADERS = $(HEADERS_NAME:%.h=$(PATH_HEADER)%.h)

flags = -IHeaders -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

diff: diff.exe
	.\diff.exe

diff.exe: DiffProgramm.o GraphDump.o DiffMain.o ReadParcer.o Simplifier.o LexicalAnalysis.o
	@g++ $(flags) DiffProgramm.o GraphDump.o DiffMain.o ReadParcer.o Simplifier.o LexicalAnalysis.o -o diff.exe

DiffProgramm.o: $(PATH_CPP)\DiffProgramm.cpp $(HEADERS) 
	@g++ -c $(flags) $(PATH_CPP)\DiffProgramm.cpp 

DiffMain.o: $(PATH_CPP)\DiffMain.cpp $(HEADERS) 
	@g++ -c $(flags) $(PATH_CPP)\DiffMain.cpp 

Simplifier.o: $(PATH_CPP)\Simplifier.cpp $(HEADERS) 
	@g++ -c $(flags) $(PATH_CPP)\Simplifier.cpp 

ReadParcer.o: $(PATH_CPP)\ReadParcer.cpp $(HEADERS) 
	@g++ -c $(flags) $(PATH_CPP)\ReadParcer.cpp 

GraphDump.o: $(PATH_CPP)\GraphDump.cpp $(HEADERS) 
	@g++ -c $(flags) $(PATH_CPP)\GraphDump.cpp 

LexicalAnalysis.o: $(PATH_CPP)\LexicalAnalysis.cpp $(HEADERS) 
	@g++ -c $(flags) $(PATH_CPP)\LexicalAnalysis.cpp 

clean:
	rm -r *.o Graphs/*.png